// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Card struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	SrcUrl    pgtype.Text        `json:"src_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
