// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddCardToCollection(ctx context.Context, arg AddCardToCollectionParams) error
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error)
	FindCardById(ctx context.Context, id uuid.UUID) (Card, error)
	ListCards(ctx context.Context) ([]Card, error)
	ListCollectionCards(ctx context.Context, collectionID uuid.UUID) ([]ListCollectionCardsRow, error)
}

var _ Querier = (*Queries)(nil)
