// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"
)

const findCardById = `-- name: FindCardById :one
SELECT id, name, src_url, created_at from cards WHERE id = $1
`

func (q *Queries) FindCardById(ctx context.Context, id int64) (Card, error) {
	row := q.db.QueryRow(ctx, findCardById, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SrcUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listCards = `-- name: ListCards :many
SELECT id, name, src_url, created_at FROM cards
`

func (q *Queries) ListCards(ctx context.Context) ([]Card, error) {
	rows, err := q.db.Query(ctx, listCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SrcUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
