// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	FindCardById(ctx context.Context, id int64) (Card, error)
	ListCards(ctx context.Context) ([]Card, error)
}

var _ Querier = (*Queries)(nil)
