// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package repo

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/shopspring/decimal"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertMTGCard = `-- name: UpsertMTGCard :batchexec
WITH existing AS (
  SELECT id FROM mtg_card
  WHERE set_id = $2 AND collector_number = $5 AND lang = $4
),
new_card AS (
  INSERT INTO "card" (game_id)
  SELECT $1
  WHERE NOT EXISTS (SELECT 1 FROM existing)
  RETURNING id
),
resolved AS (
  SELECT id FROM existing
  UNION ALL
  SELECT id FROM new_card
)
INSERT INTO mtg_card (
  id,
  set_id,
  oracle_id,
  lang,
  collector_number,
  "name",
  printed_type_line,
  printed_text,
  flavor_text,
  layout,
  cmc,
  color_identity,
  color_indicator,
  colors,
  img_small_uri,
  img_normal_uri,
  last_import_id
)
SELECT id, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
FROM resolved
ON CONFLICT (set_id, collector_number, lang) DO UPDATE SET
  oracle_id = EXCLUDED.oracle_id,
  "name" = EXCLUDED.name,
  printed_type_line = EXCLUDED.printed_type_line,
  printed_text = EXCLUDED.printed_text,
  flavor_text = EXCLUDED.flavor_text,
  layout = EXCLUDED.layout,
  cmc = EXCLUDED.cmc,
  color_identity = EXCLUDED.color_identity,
  color_indicator = EXCLUDED.color_indicator,
  colors = EXCLUDED.colors,
  img_small_uri = EXCLUDED.img_small_uri,
  img_normal_uri = EXCLUDED.img_normal_uri,
  last_import_id = EXCLUDED.last_import_id
`

type UpsertMTGCardBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertMTGCardParams struct {
	GameID          uuid.UUID           `json:"game_id"`
	SetID           uuid.UUID           `json:"set_id"`
	OracleID        uuid.UUID           `json:"oracle_id"`
	Lang            string              `json:"lang"`
	CollectorNumber string              `json:"collector_number"`
	Name            string              `json:"name"`
	PrintedTypeLine *string             `json:"printed_type_line"`
	PrintedText     *string             `json:"printed_text"`
	FlavorText      *string             `json:"flavor_text"`
	Layout          *string             `json:"layout"`
	Cmc             decimal.NullDecimal `json:"cmc"`
	ColorIdentity   *string             `json:"color_identity"`
	ColorIndicator  *string             `json:"color_indicator"`
	Colors          *string             `json:"colors"`
	ImgSmallUri     *string             `json:"img_small_uri"`
	ImgNormalUri    *string             `json:"img_normal_uri"`
	LastImportID    uuid.UUID           `json:"last_import_id"`
}

func (q *Queries) UpsertMTGCard(ctx context.Context, arg []UpsertMTGCardParams) *UpsertMTGCardBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.GameID,
			a.SetID,
			a.OracleID,
			a.Lang,
			a.CollectorNumber,
			a.Name,
			a.PrintedTypeLine,
			a.PrintedText,
			a.FlavorText,
			a.Layout,
			a.Cmc,
			a.ColorIdentity,
			a.ColorIndicator,
			a.Colors,
			a.ImgSmallUri,
			a.ImgNormalUri,
			a.LastImportID,
		}
		batch.Queue(upsertMTGCard, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertMTGCardBatchResults{br, len(arg), false}
}

func (b *UpsertMTGCardBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertMTGCardBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
