// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const addCardToCollection = `-- name: AddCardToCollection :exec
INSERT INTO collection_card (card_id, collection_id, quantity) VALUES ($1, $2, $3)
`

type AddCardToCollectionParams struct {
	CardID       uuid.UUID `json:"card_id"`
	CollectionID uuid.UUID `json:"collection_id"`
	Quantity     int16     `json:"quantity"`
}

func (q *Queries) AddCardToCollection(ctx context.Context, arg AddCardToCollectionParams) error {
	_, err := q.db.Exec(ctx, addCardToCollection, arg.CardID, arg.CollectionID, arg.Quantity)
	return err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO "collection" (user_id, "name") VALUES ($1, $2) RETURNING id, name, game_id, user_id, created_at
`

type CreateCollectionParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection, arg.UserID, arg.Name)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GameID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const findCardById = `-- name: FindCardById :one
SELECT id, oracle_id, game_id from "card" WHERE id = $1
`

func (q *Queries) FindCardById(ctx context.Context, id uuid.UUID) (Card, error) {
	row := q.db.QueryRow(ctx, findCardById, id)
	var i Card
	err := row.Scan(&i.ID, &i.OracleID, &i.GameID)
	return i, err
}

const listCards = `-- name: ListCards :many
SELECT id, oracle_id, game_id FROM "card"
`

func (q *Queries) ListCards(ctx context.Context) ([]Card, error) {
	rows, err := q.db.Query(ctx, listCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(&i.ID, &i.OracleID, &i.GameID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollections = `-- name: ListCollections :many
SELECT id, name, game_id, user_id, created_at FROM "collection" WHERE user_id = $1
`

func (q *Queries) ListCollections(ctx context.Context, userID uuid.UUID) ([]Collection, error) {
	rows, err := q.db.Query(ctx, listCollections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GameID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
