// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Card struct {
	ID     uuid.UUID `json:"id"`
	GameID uuid.UUID `json:"game_id"`
}

type Collection struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	GameID    uuid.UUID          `json:"game_id"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CollectionCard struct {
	CardID       uuid.UUID `json:"card_id"`
	CollectionID uuid.UUID `json:"collection_id"`
	Quantity     int16     `json:"quantity"`
}

type Game struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Code string    `json:"code"`
}

type MtgCard struct {
	ID              uuid.UUID           `json:"id"`
	SetID           uuid.UUID           `json:"set_id"`
	OracleID        uuid.UUID           `json:"oracle_id"`
	Lang            string              `json:"lang"`
	CollectorNumber string              `json:"collector_number"`
	Name            string              `json:"name"`
	PrintedTypeLine *string             `json:"printed_type_line"`
	PrintedText     *string             `json:"printed_text"`
	FlavorText      *string             `json:"flavor_text"`
	Layout          *string             `json:"layout"`
	Cmc             decimal.NullDecimal `json:"cmc"`
	ColorIdentity   *string             `json:"color_identity"`
	ColorIndicator  *string             `json:"color_indicator"`
	Colors          *string             `json:"colors"`
	ImgSmallUri     *string             `json:"img_small_uri"`
	ImgNormalUri    *string             `json:"img_normal_uri"`
	LastImportID    uuid.UUID           `json:"last_import_id"`
}

type MtgRelated struct {
	ID        uuid.UUID `json:"id"`
	ImportID  uuid.UUID `json:"import_id"`
	Layout    string    `json:"layout"`
	Component string    `json:"component"`
	Name      string    `json:"name"`
	TypeLine  string    `json:"type_line"`
}

type MtgRelatedCard struct {
	ID           uuid.UUID `json:"id"`
	MtgCardID    uuid.UUID `json:"mtg_card_id"`
	MtgRelatedID uuid.UUID `json:"mtg_related_id"`
}

type MtgSet struct {
	ID            uuid.UUID          `json:"id"`
	ImportID      uuid.UUID          `json:"import_id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	ReleasedAt    pgtype.Timestamptz `json:"released_at"`
	ParentSetCode *string            `json:"parent_set_code"`
	CardCount     *int32             `json:"card_count"`
}

type ScryfallImport struct {
	ID            uuid.UUID          `json:"id"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	BulkUpdatedAt pgtype.Timestamptz `json:"bulk_updated_at"`
	Status        string             `json:"status"`
}

type User struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}
