// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCardToCollection = `-- name: AddCardToCollection :exec
INSERT INTO collection_card (card_id, collection_id, quantity) VALUES ($1, $2, $3)
`

type AddCardToCollectionParams struct {
	CardID       uuid.UUID `json:"card_id"`
	CollectionID uuid.UUID `json:"collection_id"`
	Quantity     int16     `json:"quantity"`
}

func (q *Queries) AddCardToCollection(ctx context.Context, arg AddCardToCollectionParams) error {
	_, err := q.db.Exec(ctx, addCardToCollection, arg.CardID, arg.CollectionID, arg.Quantity)
	return err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO "collection" (user_id, "name") VALUES ($1, $2) RETURNING id, name, game_id, user_id, created_at
`

type CreateCollectionParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection, arg.UserID, arg.Name)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GameID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const createMTGSet = `-- name: CreateMTGSet :one
INSERT INTO mtg_set (
  import_id,
  "name",
  code,
  released_at,
  parent_set_code,
  card_count
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (code) DO UPDATE SET
  import_id = EXCLUDED.import_id,
  "name" = EXCLUDED.name,
  released_at = EXCLUDED.released_at,
  parent_set_code = EXCLUDED.parent_set_code,
  card_count = EXCLUDED.card_count
RETURNING id
`

type CreateMTGSetParams struct {
	ImportID      uuid.UUID          `json:"import_id"`
	Name          string             `json:"name"`
	Code          string             `json:"code"`
	ReleasedAt    pgtype.Timestamptz `json:"released_at"`
	ParentSetCode *string            `json:"parent_set_code"`
	CardCount     *int32             `json:"card_count"`
}

func (q *Queries) CreateMTGSet(ctx context.Context, arg CreateMTGSetParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createMTGSet,
		arg.ImportID,
		arg.Name,
		arg.Code,
		arg.ReleasedAt,
		arg.ParentSetCode,
		arg.CardCount,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createScryfallImport = `-- name: CreateScryfallImport :one
INSERT INTO scryfall_import (
  started_at,
  bulk_updated_at,
  "status"
)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateScryfallImportParams struct {
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	BulkUpdatedAt pgtype.Timestamptz `json:"bulk_updated_at"`
	Status        string             `json:"status"`
}

func (q *Queries) CreateScryfallImport(ctx context.Context, arg CreateScryfallImportParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createScryfallImport, arg.StartedAt, arg.BulkUpdatedAt, arg.Status)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findCardById = `-- name: FindCardById :one
SELECT id, game_id from "card" WHERE id = $1
`

func (q *Queries) FindCardById(ctx context.Context, id uuid.UUID) (Card, error) {
	row := q.db.QueryRow(ctx, findCardById, id)
	var i Card
	err := row.Scan(&i.ID, &i.GameID)
	return i, err
}

const findGameByCode = `-- name: FindGameByCode :one
SELECT id, name, code FROM game WHERE code = $1
`

func (q *Queries) FindGameByCode(ctx context.Context, code string) (Game, error) {
	row := q.db.QueryRow(ctx, findGameByCode, code)
	var i Game
	err := row.Scan(&i.ID, &i.Name, &i.Code)
	return i, err
}

const getScryfallImportCount = `-- name: GetScryfallImportCount :one
SELECT 
  count(id) as import_quantity 
FROM 
  scryfall_import 
WHERE 
  bulk_updated_at >= $1
`

func (q *Queries) GetScryfallImportCount(ctx context.Context, bulkUpdatedAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, getScryfallImportCount, bulkUpdatedAt)
	var import_quantity int64
	err := row.Scan(&import_quantity)
	return import_quantity, err
}

const listCards = `-- name: ListCards :many
SELECT id, game_id FROM "card" LIMIT 100 OFFSET 0
`

func (q *Queries) ListCards(ctx context.Context) ([]Card, error) {
	rows, err := q.db.Query(ctx, listCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(&i.ID, &i.GameID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollections = `-- name: ListCollections :many
SELECT id, name, game_id, user_id, created_at FROM "collection" WHERE user_id = $1
`

func (q *Queries) ListCollections(ctx context.Context, userID uuid.UUID) ([]Collection, error) {
	rows, err := q.db.Query(ctx, listCollections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GameID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScryfallImport = `-- name: UpdateScryfallImport :exec
UPDATE
  scryfall_import
SET
  finished_at = $1, "status" = $2
WHERE
  id = $3
`

type UpdateScryfallImportParams struct {
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Status     string             `json:"status"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateScryfallImport(ctx context.Context, arg UpdateScryfallImportParams) error {
	_, err := q.db.Exec(ctx, updateScryfallImport, arg.FinishedAt, arg.Status, arg.ID)
	return err
}
